# src/AppBundle/Resources/config/config.yml
parameters:
    # Blogger contact email address
    AppBundle.emails.contact_email: contact@email.com
    # Blogger max latest comments
    AppBundle.comments.latest_comment_limit: 10