
### test annotation ###

 # src/Blogger/BlogBundle/Resources/config/routing.yml
 BloggerBlogBundle_homepage:
     resource : "@AppBundle/Controller"
     type : annotation

# src/Blogger/BlogBundle/Resources/config/routing.yml
BloggerBlogBundle_about:
    resource : "@AppBundle/Controller"
    prefix:  /about
    type : annotation

# src/Blogger/BlogBundle/Resources/config/routing.yml
BloggerBlogBundle_contact:
    resource : "@AppBundle/Controller"
    prefix:  /contact
    type : annotation

# src/Blogger/BlogBundle/Resources/config/routing.yml
BloggerBlogBundle_blog_show:
    resource : "@AppBundle/Controller"
    prefix :  /{id}
    type : annotation

# src/Blogger/BlogBundle/Resources/config/routing.yml
BloggerBlogBundle_comment_create:
    resource : "@AppBundle/Controller"
    prefix:  /comment/{blog_id}
    type : annotation